swagger: "2.0"
info:
  title: realtime-locations
  description: Realtime Location
  version: 1.0.0
schemes:
  - https
paths:
  "/helloHttp":
    get:
      operationId: "helloHttp"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/helloHttp
      description: "A short message with a random number."
      responses:
        200:
          description: "Success."
          schema:
            type: string
        403:
          description: "Forbidden!"
        405:
          description: "Internal error!"
  "/shuttleCoord":
    get:
      operationId: "shuttleCoord"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/shuttleCoord
      description: "Get or post coordinate data."
      responses:
        200:
          description: "Success."
          schema:
            type: object
        403:
          description: "Forbidden!"
        405:
          description: "Internal error!"
