swagger: "2.0"
info:
  title: realtime-locations
  description: Realtime Location
  version: 1.0.0
schemes:
  - https
paths:
  "/helloHttp":
    get:
      operationId: "helloHttp"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/helloHttp
      description: "A short message with a random number."
      responses:
        200:
          description: "Success."
          schema:
            type: string
        403:
          description: "Forbidden!"
        405:
          description: "Internal error!"
  "/shuttleCoord/{id}":
    get:
      operationId: "shuttleCoordGet"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/shuttleCoord
        path_translation: CONSTANT_ADDRESS
      description: "Get most recent coordinate data."
      responses:
        200:
          description: "Success."
          schema:
            type: object
    post:
      operationId: "shuttleCoordPost"
      x-google-backend:
        address: https://us-central1-campus-shuttle-monitor.cloudfunctions.net/shuttleCoord
        path_translation: CONSTANT_ADDRESS
      description: "Post new coordinate data."
      responses:
        200:
          description: "Success."
